name: Daily updates

on:
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://www.elliotdenolf.com/rss.xml
          readme-section: posts
          max: 10
